# Generated by Django 2.1.3 on 2019-02-21 19:10

from django.db import migrations, models
import uploadtest.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadtest', '0005_auto_20190221_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=uploadtest.models.OverwriteStorage(location='C:\\Users\\IsmaelGarridoRodrigu\\Desktop\\newproject2019\\media'), upload_to='books/covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(storage=uploadtest.models.OverwriteStorage(location='C:\\Users\\IsmaelGarridoRodrigu\\Desktop\\newproject2019\\media'), upload_to='books/pdfs/'),
        ),
    ]
