# Generated by Django 2.1.3 on 2019-02-25 16:04

from django.db import migrations, models
import uploadtest.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadtest', '0007_auto_20190221_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=uploadtest.models.OverwriteStorage(), upload_to='books/covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs'),
        ),
    ]
